### ISSUE TITLE
hi can you please help?

### ISSUE THREAD

**Issue by kerenbir** [abhinavk99/crypto-bot#5]
i successful create the bot and host it in aws lightsail but when i closed the server it also shuting down the bot. the bot wont work unleash i open the server, can you help please.
thank you

**Comment by abhinavk99** [comment]
Hi, I'm not familiar with AWS lightsail, but I'm assuming you're SSHing to the server and when you exit, the bot stops running, which happens because the bot is running within the shell process and when you exit, the shell process ends so the bot ends. If you want to keep it running, you can run the bot using a command line program called pm2. You can find guides online about it. I hope that helps.

**Comment by kerenbir** [comment]
thank you very much now its online

**Comment by abhinavk99** [comment]
You're welcome
